controlnet_additional_kwargs:
  set_noisy_sample_input_to_zero:     true
  use_simplified_condition_embedding: true
  conditioning_channels:              4

  use_motion_module:         true
  motion_module_resolutions: [1,2,4,8]
  motion_module_mid_block:   false
  motion_module_type:        "Vanilla"

  motion_module_kwargs:
    num_attention_heads:                8
    num_transformer_block:              1
    attention_block_types:              [ "Temporal_Self" ]
    temporal_position_encoding:         true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div:         1
