GhibliBackground:
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/CounterfeitV30_25.safetensors"
  lora_model_path: "models/DreamBooth_LoRA/lora_Ghibli_n3.safetensors"
  lora_alpha: 1.0

  seed:           [8775748474469046618, 5893874876080607656, 11911465742147695752, 12437784838692000640]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "best quality,single build,architecture, blue_sky, building,cloudy_sky, day, fantasy, fence, field, house, build,architecture,landscape, moss, outdoors, overgrown, path, river, road, rock, scenery, sky, sword, tower, tree, waterfall"
    - "black_border, building, city, day, fantasy, ice, landscape, letterboxed, mountain, ocean, outdoors, planet, scenery, ship, snow, snowing, water, watercraft, waterfall, winter"
    - ",mysterious sea area, fantasy,build,concept"
    - "Tomb Raider,Scenography,Old building"

  n_prompt:
    - "easynegative,bad_construction,bad_structure,bad_wail,bad_windows,blurry,cloned_window,cropped,deformed,disfigured,error,extra_windows,extra_chimney,extra_door,extra_structure,extra_frame,fewer_digits,fused_structure,gross_proportions,jpeg_artifacts,long_roof,low_quality,structure_limbs,missing_windows,missing_doors,missing_roofs,mutated_structure,mutation,normal_quality,out_of_frame,owres,poorly_drawn_structure,poorly_drawn_house,signature,text,too_many_windows,ugly,username,uta,watermark,worst_quality"
